component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/com/.*
- ./bin/com/mvnforum/.*
- ./bin/com/mvnforum/admin/.*
- ./bin/com/mvnforum/admin/importexport/.*
- ./bin/com/mvnforum/admin/importexport/jive/.*
- ./bin/com/mvnforum/admin/importexport/mvnforum/.*
- ./bin/com/mvnforum/auth/.*
- ./bin/com/mvnforum/auth/service/.*
- ./bin/com/mvnforum/auth/service/impl/.*
- ./bin/com/mvnforum/categorytree/.*
- ./bin/com/mvnforum/categorytree/impl/.*
- ./bin/com/mvnforum/common/.*
- ./bin/com/mvnforum/common/kg/.*
- ./bin/com/mvnforum/db/.*
- ./bin/com/mvnforum/db/common/.*
- ./bin/com/mvnforum/db/jdbc/.*
- ./bin/com/mvnforum/event/.*
- ./bin/com/mvnforum/jaxb/.*
- ./bin/com/mvnforum/jaxb/dao/.*
- ./bin/com/mvnforum/jaxb/db/.*
- ./bin/com/mvnforum/jaxb/db/impl/.*
- ./bin/com/mvnforum/jaxb/db/impl/runtime/.*
- ./bin/com/mvnforum/jaxb/util/.*
- ./bin/com/mvnforum/search/.*
- ./bin/com/mvnforum/search/albumitem/.*
- ./bin/com/mvnforum/search/attachment/.*
- ./bin/com/mvnforum/search/member/.*
- ./bin/com/mvnforum/search/post/.*
- ./bin/com/mvnforum/service/.*
- ./bin/com/mvnforum/service/impl/.*
- ./bin/com/mvnforum/user/.*
- ./bin/com/mvnsoft/.*
- ./bin/com/mvnsoft/auth/.*
- ./bin/com/mvnsoft/auth/realm/.*
- ./bin/com/mvnsoft/mvnad/.*
- ./bin/com/mvnsoft/mvnad/admin/.*
- ./bin/com/mvnsoft/mvnad/db/.*
- ./bin/com/mvnsoft/mvnad/db/jdbc/.*
- ./bin/com/mvnsoft/mvnad/delivery/.*
- ./bin/com/mvnsoft/mvnad/service/.*
- ./bin/com/mvnsoft/mvnad/service/impl/.*
- ./bin/com/mvnsoft/mvnad/user/.*
- ./bin/java/.*
- ./bin/java/sql/.*
- ./bin/net/.*
- ./bin/net/myvietnam/.*
- ./bin/net/myvietnam/mvncore/.*
- ./bin/net/myvietnam/mvncore/configuration/.*
- ./bin/net/myvietnam/mvncore/db/.*
- ./bin/net/myvietnam/mvncore/exception/.*
- ./bin/net/myvietnam/mvncore/filter/.*
- ./bin/net/myvietnam/mvncore/gui/.*
- ./bin/net/myvietnam/mvncore/i18n/.*
- ./bin/net/myvietnam/mvncore/info/.*
- ./bin/net/myvietnam/mvncore/interceptor/.*
- ./bin/net/myvietnam/mvncore/interceptor/sample/.*
- ./bin/net/myvietnam/mvncore/misc/.*
- ./bin/net/myvietnam/mvncore/mvnframework/.*
- ./bin/net/myvietnam/mvncore/security/.*
- ./bin/net/myvietnam/mvncore/service/.*
- ./bin/net/myvietnam/mvncore/service/impl/.*
- ./bin/net/myvietnam/mvncore/servlet/.*
- ./bin/net/myvietnam/mvncore/servlet/filter/.*
- ./bin/net/myvietnam/mvncore/taglib/.*
- ./bin/net/myvietnam/mvncore/thirdparty/.*
- ./bin/net/myvietnam/mvncore/thirdparty/commonj/.*
- ./bin/net/myvietnam/mvncore/thirdparty/commonj/timers/.*
- ./bin/net/myvietnam/mvncore/thirdparty/commonj/util/.*
- ./bin/net/myvietnam/mvncore/thirdparty/commonj/work/.*
- ./bin/net/myvietnam/mvncore/util/.*
- ./bin/net/myvietnam/mvncore/web/.*
- ./bin/net/myvietnam/mvncore/web/fileupload/.*
- ./bin/net/myvietnam/mvncore/web/fileupload/disk/.*
- ./bin/net/myvietnam/mvncore/web/fileupload/servlet/.*
- ./bin/net/myvietnam/mvncore/web/impl/.*
- ./bin/org/.*
- ./bin/org/mvnforum/.*
- ./bin/org/mvnforum/phpbb2mvnforum/.*
- ./bin/org/mvnforum/phpbb2mvnforum/db/.*
- ./bin/org/mvnforum/phpbb2mvnforum/db/jdbc/.*
- ./bin/org/mvnforum/util/.*
- ./lib/.*
- ./mvnad/.*
- ./mvnad/docs/.*
- ./mvnad/extension/.*
- ./mvnad/i18n/.*
- ./mvnad/properties/.*
- ./mvnad/sql/.*
- ./mvnad/sql/hsqldb/.*
- ./mvnad/sql/upgrade/.*
- ./mvnforum/.*
- ./mvnforum/contrib/.*
- ./mvnforum/contrib/create_hsqldb/.*
- ./mvnforum/contrib/daily_mvnforum/.*
- ./mvnforum/contrib/daily_mvnforum/bin/.*
- ./mvnforum/contrib/icons/.*
- ./mvnforum/contrib/icons/icons_01/.*
- ./mvnforum/contrib/jdbcRealm/.*
- ./mvnforum/contrib/jdbcRealm/conf/.*
- ./mvnforum/contrib/jdbcRealm/docs/.*
- ./mvnforum/contrib/jdbcRealm/lib/.*
- ./mvnforum/contrib/lucene_prebuild/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvncms/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvncms/search/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvncms/search/content/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_enterprise_only/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_enterprise_only/search/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_enterprise_only/search/albumitem/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_enterprise_only/search/attachment/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_enterprise_only/search/member/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_enterprise_only/search/post/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_only/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_only/search/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_only/search/attachment/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_only/search/member/.*
- ./mvnforum/contrib/lucene_prebuild/lucene_mvnforum_only/search/post/.*
- ./mvnforum/contrib/phpBB2mvnForum_method1/.*
- ./mvnforum/contrib/phpbb2mvnforum/.*
- ./mvnforum/contrib/phpbb2mvnforum/properties/.*
- ./mvnforum/contrib/phpbb2mvnforum-jaxb/.*
- ./mvnforum/contrib/phpbb2mvnforum-jaxb/docs/.*
- ./mvnforum/contrib/phpbb2mvnforum-jaxb/lib/.*
- ./mvnforum/contrib/phpbb2mvnforum-jaxb/schema/.*
- ./mvnforum/contrib/template/.*
- ./mvnforum/contrib/template/diendandientu/.*
- ./mvnforum/contrib/template/diendandientu/mvnplugin/.*
- ./mvnforum/contrib/template/diendandientu/mvnplugin/mvnforum/.*
- ./mvnforum/contrib/template/diendandientu/mvnplugin/mvnforum/css/.*
- ./mvnforum/contrib/template/diendandientu/mvnplugin/mvnforum/images/.*
- ./mvnforum/contrib/template/diendandientu/mvnplugin/mvnforum/user/.*
- ./mvnforum/database_schema/.*
- ./mvnforum/docbook/.*
- ./mvnforum/docbook/antlib/.*
- ./mvnforum/docbook/repository/.*
- ./mvnforum/docbook/repository/include/.*
- ./mvnforum/docbook/stylesheet/.*
- ./mvnforum/docbook2/.*
- ./mvnforum/docbook2/figure/.*
- ./mvnforum/docbook2/whatnews/.*
- ./mvnforum/docbook2/xml/.*
- ./mvnforum/docbook2/xml/include/.*
- ./mvnforum/docs/.*
- ./mvnforum/docs/docs_for_builds/.*
- ./mvnforum/docs/docs_for_builds/mvnforum_mvnad_bin/.*
- ./mvnforum/docs/docs_for_builds/mvnforum_mvnad_bundle/.*
- ./mvnforum/docs/images/.*
- ./mvnforum/driver/.*
- ./mvnforum/dtd/.*
- ./mvnforum/extension/.*
- ./mvnforum/i18n/.*
- ./mvnforum/i18n/tool/.*
- ./mvnforum/lib/.*
- ./mvnforum/properties/.*
- ./mvnforum/sql/.*
- ./mvnforum/sql/hsqldb/.*
- ./mvnforum/sql/upgrade/.*
- ./mvnforum/sql/upgrade/1_0_0_beta2_to_1_0_0_beta3/.*
- ./mvnforum/sql/upgrade/1_0_0_beta3_to_1_0_0_rc1/.*
- ./mvnforum/sql/upgrade/1_0_0_rc1_to_1_0_0_rc2/.*
- ./mvnforum/sql/upgrade/1_0_0_rc3_to_1_0_0_rc4/.*
- ./mvnforum/sql/upgrade/1_0_0_rc4_to_1_0_0_ga/.*
- ./mvnforum/sql/upgrade/1_0_ga_to_1_1_ga/.*
- ./mvnforum/template/.*
- ./myvietnam/.*
- ./myvietnam/docs/.*
- ./myvietnam/i18n/.*
- ./myvietnam/i18n/tool/.*
- ./myvietnam/lib/.*
- ./myvietnam/properties/.*
- ./myvietnam/tld/.*
